# Generated by Django 2.2.8 on 2019-12-18 07:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('teacher', models.CharField(max_length=200)),
                ('count', models.IntegerField(default=0)),
                ('attendence', models.IntegerField(default=0, help_text='0 imply no leniency and 10 imply very lenient', validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)])),
                ('marks', models.IntegerField(default=0, help_text='0 imply no leniency and 10 imply very lenient', validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)])),
                ('quality', models.IntegerField(default=0, help_text='0 imply low quality and 10 imply high quality', validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='elective.Course')),
            ],
        ),
    ]
