# Generated by Django 2.2.6 on 2019-12-18 09:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elective', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='attendence',
            field=models.IntegerField(default=0, help_text='0 imply no leniency and 10 imply very lenient', validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='feedback',
            name='marks',
            field=models.IntegerField(default=0, help_text='0 imply no leniency and 10 imply very lenient', validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='feedback',
            name='name',
            field=models.CharField(default='xyz', max_length=200),
        ),
        migrations.AddField(
            model_name='feedback',
            name='quality',
            field=models.IntegerField(default=0, help_text='0 imply low quality and 10 imply high quality', validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='feedback',
            name='teacher',
            field=models.CharField(default='xyz', max_length=200),
        ),
    ]
